version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    ports:
      - "5101:3000"
    links:
      - mongo_api
  nginx_api:
    build:
      context: .
      dockerfile: ./Dockerfile-nginx.development
    ports:
      - "80:80"
    volumes:
      - ./nginx-development.conf:/etc/nginx/nginx.conf
    links:
      - api
    command:
      [
        "./wait-for-it.sh",
        "-t",
        "20",
        "api:3000",
        "--",
        "nginx",
        "-g",
        "daemon off;"
      ]
